const assert = require("assert");
const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const appPath = path.join(root, "app.js");
const htmlPath = path.join(root, "index.html");
const cssPath = path.join(root, "styles.css");
const sqlPath = path.join(root, "supabase-schema.sql");
const aprovadoBookmarkletPath = path.join(root, "bookmarklet-aprovado.txt");

const app = fs.readFileSync(appPath, "utf8");
const html = fs.readFileSync(htmlPath, "utf8");
const css = fs.readFileSync(cssPath, "utf8");
const sql = fs.readFileSync(sqlPath, "utf8");
const aprovadoBookmarklet = fs.readFileSync(aprovadoBookmarkletPath, "utf8");

execFileSync(process.execPath, ["--check", appPath], { stdio: "inherit" });

assert(html.includes("dailyReviewList"), "Painel diario nao encontrado no HTML.");
assert(html.includes("editalManualForm"), "Formulario manual do edital nao encontrado.");
assert(html.includes("accountStatusList"), "Status da conta nao encontrado.");
assert(html.includes("20260717-backup-review-report"), "Cache do HTML nao foi atualizado para backup, revisao e relatorios.");
assert(html.includes("supabase-config.js?v=20260717-backup-review-report"), "Cache-buster do supabase-config.js ausente.");
assert(html.includes('id="studyCanvas" width="620" height="330"'), "Canvas do painel deve ter altura suficiente para nao cortar o resumo visual.");
assert(html.includes('id="questionCancelEditBtn"'), "Cancelamento de edicao de questoes ausente.");
assert(html.includes('id="questionSubject"'), "Seletor de materia em questoes ausente.");
assert(html.includes('<option value="note">'), "Tipo Anotacao nos materiais de apoio ausente.");
assert(html.includes('id="legalMaterialCancelEditBtn"'), "Cancelamento de edicao de leis/tabelas/anotacoes ausente.");
assert(html.includes('id="noteCancelEditBtn"'), "Cancelamento de edicao de anotacoes ausente.");
assert(html.includes("unpkg.com/@supabase/supabase-js@2"), "CDN alternativo do SDK Supabase ausente.");
assert(html.includes("cancelSubjectEditBtn"), "Cancelamento de edicao de materia ausente.");
assert(html.includes("cancelTopicEditBtn"), "Cancelamento de edicao de assunto ausente.");
assert(html.includes("externalStudyImportInput"), "Importador externo de estudos ausente.");
assert(html.includes("bookmarklet-aprovado.txt"), "Link do coletor do Aprovado ausente.");
assert(html.includes("data-view=\"concursos\""), "Aba Concursos ausente.");
assert(html.includes("competitionForm"), "Formulario de concursos ausente.");
assert(html.includes("timerCompetition"), "Seletor de concurso no Pomodoro ausente.");
assert(html.includes("studyCompetition"), "Seletor de concurso no registro manual ausente.");
assert(html.includes("data-subject-color"), "Cores rapidas de materia ausentes.");
assert(html.includes("reportTimelineChart"), "Grafico de linha do tempo dos relatorios ausente.");
assert(html.includes("reportTimelineLegend"), "Legenda de cores dos relatorios ausente.");
assert(html.includes("reportCustomForm"), "Periodo customizado dos relatorios ausente.");
assert(html.includes("data-question-precision-range=\"day\""), "Filtro diario de precisao ausente.");
assert(html.includes("questionPrecisionSummary"), "Resumo de precisao por periodo ausente.");
assert(html.includes("questionReviewReminders"), "Lembretes de revisao por pior desempenho ausentes.");
assert(html.includes("caseCourtSelect"), "Seletor de tribunal no cadastro de jurisprudencia ausente.");
assert(html.includes("data-case-search-scope=\"all\""), "Busca geral STJ + STF ausente.");
assert(html.includes("backupShortcutPanel"), "Atalho visivel de backup no painel ausente.");
assert(html.includes("data-action=\"downloadBackup\""), "Acao direta de download de backup ausente.");
assert(html.includes("reportCompetitionFilter"), "Filtro de relatorios por concurso ausente.");
assert(html.includes("reportCompetitionHint"), "Resumo do filtro de concurso ausente.");

assert(app.includes("function renderDailyReview"), "renderDailyReview ausente.");
assert(!app.includes("searchable-select"), "Seletores customizados nao devem existir no JS.");
assert(app.includes("function deleteCurrentProfileData"), "Exclusao de dados da conta ausente.");
assert(app.includes("deleteEditalItem"), "Remocao individual de item do edital ausente.");
assert(app.includes("email: user.email"), "Sincronizacao do e-mail no Supabase ausente.");
assert(app.includes("editSubject"), "Edicao de materias ausente.");
assert(app.includes("editTopic"), "Edicao de assuntos ausente.");
assert(app.includes("isStrongOnlinePassword"), "Validacao de senha forte online ausente.");
assert(app.includes("Brevo bloqueou"), "Mensagem amigavel de SMTP/Brevo ausente.");
assert(app.includes("supabase-config.js foi publicado atualizado"), "Mensagem de conexao Supabase nao orienta cache/publicacao.");
assert(app.includes("createSupabaseFallbackClient"), "Cliente fallback do Supabase ausente.");
assert(app.includes("SUPABASE_FALLBACK_SESSION_KEY"), "Sessao fallback do Supabase ausente.");
assert(app.includes("importExternalStudyFile"), "Importador de estudos externos ausente.");
assert(app.includes("parseExternalStudyImport"), "Parser de estudos externos ausente.");
assert(app.includes("function normalizeCompetition"), "Normalizacao de concursos ausente.");
assert(app.includes("function renderCompetitions"), "Renderizacao de concursos ausente.");
assert(app.includes("competitionId"), "Vinculo de estudo com concurso ausente.");
assert(app.includes("updateSubjectColorPresetState"), "Controle das cores rapidas de materia ausente.");
assert(app.includes("function renderReportTimeline"), "Renderizacao do grafico empilhado dos relatorios ausente.");
assert(app.includes("function getReportPeriodMeta"), "Calculo de periodo dos relatorios ausente.");
assert(app.includes("reportGroup"), "Agrupamento por materias/conteudos nos relatorios ausente.");
assert(app.includes("activeQuestionEditId"), "Edicao de questoes ausente no estado.");
assert(app.includes("editLegalMaterial"), "Edicao de materiais de apoio ausente.");
assert(app.includes("renderLegalMaterialGroups"), "Separacao de leis, tabelas, anotacoes e imagens ausente.");
assert(app.includes("questionPrecisionRange"), "Estado do periodo de precisao ausente.");
assert(app.includes("renderQuestionReviewReminders"), "Renderizacao dos lembretes de revisao ausente.");
assert(app.includes("syncScopedTopicSelect(\"#questionSubject\", \"#questionTopic\""), "Assuntos de questoes nao estao vinculados a materia.");
assert(app.includes("[\"#questionSubject\", \"#questionTopic\", null, { includeEmpty: false }]"), "Evento de materia em questoes ausente.");
assert(app.includes("state.studyLogs = state.studyLogs.map((log) => (log.topicId === id"), "Estudos devem ser preservados na materia ao excluir assunto.");
assert(!app.includes("state.studyLogs = state.studyLogs.filter((log) => log.topicId !== id)"), "Excluir assunto nao pode apagar estudos registrados.");
assert(app.includes("function looksLikeLegalArticleText"), "Deteccao de texto juridico para evitar tabela automatica ausente.");
assert(app.includes("function parsePlainTextTableRows"), "Deteccao criteriosa de tabela em texto ausente.");
assert(app.includes("bindRichPasteGuards"), "Protecao de colagem em todos os editores ricos ausente.");
assert(app.includes("FORM_DRAFT_KEY_PREFIX"), "Rascunho local dos formularios ausente.");
assert(app.includes("STATE_BACKUP_KEY_PREFIX"), "Backup local defensivo do estado ausente.");
assert(app.includes("bindUnsavedDraftTracking"), "Monitoramento de rascunhos nao foi instalado.");
assert(app.includes("caseFormCourt"), "Tribunal do formulario de jurisprudencia nao foi separado da aba ativa.");
assert(app.includes("caseSearchScope"), "Escopo da busca de jurisprudencias ausente.");
assert(app.includes("activeCaseEditCourt"), "Edicao de jurisprudencia deve preservar o tribunal original.");
assert(app.includes("reportCompetitionId"), "Estado do filtro de relatorio por concurso ausente.");
assert(app.includes("function reportStudyLogMatchesCompetition"), "Filtro de estudos por concurso ausente.");
assert(app.includes("function reportQuestionLogMatchesCompetition"), "Filtro de questoes por concurso ausente.");
assert(app.includes("competitionFocusSubject"), "Revisao diaria nao sugere foco por concurso.");
assert(app.includes("staleSubject"), "Revisao diaria nao identifica materia sem estudo recente.");
assert(app.includes("downloadBackupFile();"), "Botao rapido de backup nao dispara download.");

assert(css.includes(".daily-review-grid"), "CSS do painel diario ausente.");
assert(css.includes(".account-status-row"), "CSS do status da conta ausente.");
assert(!css.includes(".searchable-select"), "CSS antigo do seletor customizado ainda existe.");
assert(css.includes(".topic-item-top"), "Layout novo dos assuntos nao foi aplicado.");
assert(css.includes(".subject-card-actions"), "Layout das acoes de materia nao foi aplicado.");
assert(css.includes("#logoutProfileBtn"), "Layout do painel de login nao foi ajustado.");
assert(css.includes(".external-import-preview"), "CSS do importador externo ausente.");
assert(css.includes(".competition-board"), "CSS da aba concursos ausente.");
assert(css.includes(".subject-color-palette"), "CSS da paleta de cores de materia ausente.");
assert(css.includes(".report-stacked-bar"), "CSS das barras empilhadas dos relatorios ausente.");
assert(css.includes(".report-legend-item"), "CSS da legenda de materias dos relatorios ausente.");
assert(css.includes("overflow: hidden"), "Grafico dos relatorios nao deve criar rolagem interna.");
assert(css.includes(".legal-material-group-title"), "CSS da separacao por tipo de material ausente.");
assert(css.includes(".review-reminder-card"), "CSS dos lembretes de revisao ausente.");
assert(css.includes(".backup-shortcut-panel"), "CSS do atalho de backup ausente.");
assert(css.includes(".report-filter-row"), "CSS do filtro de concurso em relatorios ausente.");

assert(aprovadoBookmarklet.startsWith("javascript:"), "Bookmarklet do Aprovado deve comecar com javascript:.");
assert(aprovadoBookmarklet.includes("estudos-track-external-study-v1"), "Bookmarklet do Aprovado nao gera schema esperado.");

assert(/enable row level security/i.test(sql), "RLS nao esta habilitado no SQL.");
assert(sql.includes("auth.uid() = user_id"), "Politicas por usuario ausentes no SQL.");
assert(/create trigger set_study_profiles_updated_at/i.test(sql), "Trigger de updated_at ausente.");

console.log("Smoke tests OK: estrutura principal validada.");
